name: Deploy to cPanel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.edstack.xyz
        username: edstack
        password: edstackhq@2025
        local-dir: './dist/' 
        server-dir: '/public_html/'  
